### ISSUE TITLE
Errors running in NetPyNE (runs in NEURON)

### ISSUE THREAD

**Issue by sanjayankur31** [sanjayankur31/Human-L2-3-Cortical-Microcircuit#6]
Errors out when trying to run in NetPyNE, but seems to run fine in NEURON (we get nan values because some exponential goes very large, but it does complete the simulation)

## Steps to reproduce NEURON run:

```
python create_network.py 0.01
pynml -java_max_memory 8G LEMS_HL23_0.01_Sim.xml -neuron
nrnivmodl
python LEMS_HL23_0.01_Sim_nrn.py
```

### Results

```

    Starting simulation in NEURON of 2000ms generated from NeuroML2 model...
...
Adding projection: proj_804_852, from HL23SST_pop_804 to HL23PV_pop_852 with synapse HL23SST_HL23PV_ProbUDFsyn, 13 connection(s)
Adding projection: proj_804_864, from HL23SST_pop_804 to HL23PV_pop_864 with synapse HL23SST_HL23PV_ProbUDFsyn, 13 connection(s)
Adding projection: proj_852_776, from HL23PV_pop_852 to HL23PYR_pop_776 with synapse HL23PV_HL23PYR_ProbUDFsyn, 17 connection(s)
Adding projection: proj_936_804, from HL23VIP_pop_936 to HL23SST_pop_804 with synapse HL23VIP_HL23SST_ProbUDFsyn, 9 connection(s)
Adding projection: proj_936_816, from HL23VIP_pop_936 to HL23SST_pop_816 with synapse HL23VIP_HL23SST_ProbUDFsyn, 9 connection(s)
Adding projection: proj_936_852, from HL23VIP_pop_936 to HL23PV_pop_852 with synapse HL23VIP_HL23PV_ProbUDFsyn, 11 connection(s)
Processing 46 input lists
Finished processing 46 input lists
Setting up the network to simulate took 0.823113 seconds
Running a simulation of 2000.0ms (dt = 0.025ms; seed=123)
exp(719.121) out of range, returning exp(700)
exp(2655.19) out of range, returning exp(700)
exp(2145.86) out of range, returning exp(700)
exp(889.908) out of range, returning exp(700)
No more errno warnings during this execution
Finished NEURON simulation in 107.223391 seconds (1.787057 mins)...
Saving results at t=2000.0000000050845...
Saved data to: time.dat
Saved data to: HL23Net_0.01.v.dat
Finished saving results in 0.323251 seconds
Done
```

## NetPyNE run

```
rm -rf *.hoc *.mod x86_64
pynml -java_max_memory 8G LEMS_HL23_0.01_Sim.xml -netpyne # completes without errors
nrnivmodl
python LEMS_HL23_0.01_Sim_netpyne.py


```
### Results
```
# lots of verbose output printing out whole cell neuroml files and so on (should probably disable this)
# after a while (much slower than NEURON at this point)
...

Finished import of NeuroML2; populations vs gids NML has calculated:
   HL23PYR_pop_0: [0]
   HL23PYR_pop_397: [1]
   HL23PYR_pop_794: [2]
   HL23PYR_pop_388: [3]
   HL23PYR_pop_785: [4]
   HL23PYR_pop_379: [5]
   HL23PYR_pop_776: [6]
   HL23PYR_pop_394: [7]
   HL23SST_pop_804: [8]
   HL23SST_pop_816: [9]
   HL23PV_pop_852: [10]
   HL23PV_pop_864: [11]
   HL23VIP_pop_924: [12]
   HL23VIP_pop_936: [13]

Start time:  2023-09-12 18:30:10.655897

Creating network of 14 cell populations on 1 hosts...
Traceback (most recent call last):
  File "/home/asinha/Documents/02_Code/00_mine/models/Human-L2-3-Cortical-Microcircuit/NeuroML2/LEMS_HL23_0.01_Sim_netpyne.py", line 334, in <module>
    ns.run()
  File "/home/asinha/Documents/02_Code/00_mine/models/Human-L2-3-Cortical-Microcircuit/NeuroML2/LEMS_HL23_0.01_Sim_netpyne.py", line 218, in run
    self.gids = sim.importNeuroML2SimulateAnalyze(self.nml2_file_name,self.simConfig)
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/sim/wrappers.py", line 635, in importNeuroML2SimulateAnalyze
    return sim.importNeuroML2(fileName, simConfig, simulate=True, analyze=True)
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/conversion/neuromlFormat.py", line 1690, in importNeuroML2
    cells = sim.net.createCells()  # instantiate network cells based on defined populations
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/network/network.py", line 99, in createCells
    newCells = ipop.createCells()  # create cells for this pop using Pop method
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/network/pop.py", line 79, in createCells
    cells = self.createCellsList()
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/network/pop.py", line 395, in createCellsList
    cells.append(self.cellModelClass(gid, cellTags))  # instantiate Cell object
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/cell/compartCell.py", line 59, in __init__
    self.create()  # create cell
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/cell/compartCell.py", line 121, in create
    self.createNEURONObj(
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/cell/compartCell.py", line 379, in createNEURONObj
    mechInsertError |= self._addDistributedMechs(sectName, sectParams, cellType, cellVars)
  File "/home/asinha/.local/share/virtualenvs/neuroml-310/lib/python3.10/site-packages/netpyne/cell/compartCell.py", line 477, in _addDistributedMechs
    setattr(getattr(seg, mechName), mechParamName, mechParamValueFinal)
AttributeError: 'nrn.Mechanism' object has no attribute 'e'

```

## System info

```
$ pip list | grep -iE '(neuroml|netpyne|neuron)'
libNeuroML                    0.5.3
netpyne                       1.0.4.2
neuromllite                   0.5.6
NEURON                        8.2.2
pyNeuroML                     1.0.10   /home/asinha/Documents/02_Code/00_mine/NeuroML/software/pyNeuroML

$ python --version
Python 3.10.13

$ pynml -version
pyNeuroML v1.0.10 (libNeuroML v0.5.3, jNeuroML v0.12.2)
```

**Comment by sanjayankur31** [comment]
Also seeing this in CI now. It's related to the use of the Tonic inhibition bits from the looks of it.

**Comment by sanjayankur31** [comment]
Fixed it. Had used "nonspecific" instead of "non_specific". I wonder if we can do something to point out to the user that a weird value has been used in the "ion" field?

Fixed in https://github.com/sanjayankur31/Human-L2-3-Cortical-Microcircuit/commit/d5425ff40ca49ea6279a7d0e0f88d042f9049a9e
